config/routes.rb
Postulation::Engine.routes.draw do
  resources :postulation_processes

end

app/models/postulation/postulation_process.rb
module Postulation
  class PostulationProcess < ActiveRecord::Base
  end
end

app/controllers/postulation/application_controller.rb
module Postulation
  class ApplicationController < ActionController::Base
  end
end

app/controllers/postulation/postulation_processes_controller.rb
require_dependency "postulation/application_controller"

module Postulation
  class PostulationProcessesController < ApplicationController
    before_action :set_postulation_process, only: [:show, :edit, :update, :destroy]

    # GET /postulation_processes
    def index
      @postulation_processes = PostulationProcess.all
    end

    # GET /postulation_processes/1
    def show
    end

    # GET /postulation_processes/new
    def new
      @postulation_process = PostulationProcess.new
    end

    # GET /postulation_processes/1/edit
    def edit
    end

    # POST /postulation_processes
    def create
      @postulation_process = PostulationProcess.new(postulation_process_params)

      if @postulation_process.save
        redirect_to @postulation_process, notice: 'Postulation process was successfully created.'
      else
        render action: 'new'
      end
    end

    # PATCH/PUT /postulation_processes/1
    def update
      if @postulation_process.update(postulation_process_params)
        redirect_to @postulation_process, notice: 'Postulation process was successfully updated.'
      else
        render action: 'edit'
      end
    end

    # DELETE /postulation_processes/1
    def destroy
      @postulation_process.destroy
      redirect_to postulation_processes_url, notice: 'Postulation process was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_postulation_process
        @postulation_process = PostulationProcess.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def postulation_process_params
        params.require(:postulation_process).permit(:name, :place, :description, :salary)
      end
  end
end

app/helpers/postulation/application_helper.rb
module Postulation
  module ApplicationHelper
  end
end

app/helpers/postulation/postulation_processes_helper.rb
module Postulation
  module PostulationProcessesHelper
  end
end

app/views/layouts/postulation/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Postulation</title>
  <%= stylesheet_link_tag    "postulation/application", media: "all" %>
  <%= javascript_include_tag "postulation/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/postulation/postulation_processes/_form.html.erb
<%= form_for(@postulation_process) do |f| %>
  <% if @postulation_process.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@postulation_process.errors.count, "error") %> prohibited this postulation_process from being saved:</h2>

      <ul>
      <% @postulation_process.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :place %><br>
    <%= f.text_field :place %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :salary %><br>
    <%= f.number_field :salary %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/postulation/postulation_processes/edit.html.erb
<h1>Editing postulation_process</h1>

<%= render 'form' %>

<%= link_to 'Show', @postulation_process %> |
<%= link_to 'Back', postulation_processes_path %>

app/views/postulation/postulation_processes/index.html.erb
<h1>Listing postulation_processes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Place</th>
      <th>Description</th>
      <th>Salary</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @postulation_processes.each do |postulation_process| %>
      <tr>
        <td><%= postulation_process.name %></td>
        <td><%= postulation_process.place %></td>
        <td><%= postulation_process.description %></td>
        <td><%= postulation_process.salary %></td>
        <td><%= link_to 'Show', postulation_process %></td>
        <td><%= link_to 'Edit', edit_postulation_process_path(postulation_process) %></td>
        <td><%= link_to 'Destroy', postulation_process, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Postulation process', new_postulation_process_path %>

app/views/postulation/postulation_processes/new.html.erb
<h1>New postulation_process</h1>

<%= render 'form' %>

<%= link_to 'Back', postulation_processes_path %>

app/views/postulation/postulation_processes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @postulation_process.name %>
</p>

<p>
  <strong>Place:</strong>
  <%= @postulation_process.place %>
</p>

<p>
  <strong>Description:</strong>
  <%= @postulation_process.description %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @postulation_process.salary %>
</p>

<%= link_to 'Edit', edit_postulation_process_path(@postulation_process) %> |
<%= link_to 'Back', postulation_processes_path %>